include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "build/**"
    - "bin/cache/**"
    - "assets/**"
    - "ios/**"
    - "android/**"
    - "**.freezed.dart"
    - "**.cached.dart"
    - "**.g.dart"
    - "**.gr.dart"
    - "**.config.dart"
    - "**.chopper.dart"
