name: test_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: "3.24.1"

dependencies:
  chopper: 8.0.1+1
  easy_localization: ^3.0.3
  flutter:
    sdk: flutter
  flutter_bloc: 8.1.6
  flutter_hooks: 0.20.5
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^2.4.4
  get_it: 7.7.0
  go_router: ^14.3.0
  hooked_bloc: ^1.4.3
  injectable: ^2.4.1
  json_annotation: ^4.8.0
  mocktail: ^1.0.0
  rxdart: 0.27.7

dev_dependencies:
  build_runner: ^2.4.9
  chopper_generator: 8.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  flutter_lints: ^4.0.0
  go_router_builder: ^2.4.0
  injectable_generator: ^2.6.1
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/images/svg/
